name: Build APK Flutter

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build Aplikasi Android
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Ambil Kode Proyek
        uses: actions/checkout@v4

      - name: 🛠️ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.0'
          channel: 'stable'

      - name: 📱 Konfigurasi Android SDK
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          flutter config --android-sdk "$ANDROID_HOME"
          flutter config --no-android-studio

      - name: 📦 Install Dependensi
        run: flutter pub get

      - name: ✅ Cek Kode (dilewati sementara)
        run: echo "Melewati pengecekan kode..."

      - name: 🤖 Build APK Release
        run: flutter build apk --release --no-tree-shake-icons

      - name: 📤 Upload APK Hasil Build
        uses: actions/upload-artifact@v4
        with:
          name: Tutorial-Linux-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30
